### ISSUE TITLE
Extension breaks lolreader

### ISSUE THREAD

**Issue by rikai** [1lann/lolreader#8]
The [HTTPS Everywhere extension](https://www.eff.org/https-everywhere) completely breaks lolreader, or at least the already hosted version.

Not sure if there's anything that can be done about this, but figured i'd file a bug about it since it broke things for several of my friends. :+1:

**Comment by 1lann** [comment]
Thanks, fixed. I'm currently busy working on other projects, so I might not ever complete the other features you had suggested :disappointed:. You can submit your own pull requests to implement these features and other improvements this if you would like, although the current codebase is REALLY messy and even I, myself, don't want to touch it.

**Comment by rikai** [comment]
I might have a look at adding the other game modes, that one seems simple enough to build off of the existing framework, but i wouldn't know where to even start for the aliasing stuff. That's a bit over my head.
